# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*

resources:
- repo: self

variables:
  projectName: 'Eco Phase 2'
  DOCKER_ID: $(DOCKER_ID)

stages:
- stage: Build
  displayName: Build images
  jobs:  
  - job: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    timeoutInMinutes: 30
    displayName: Build images for development
    steps:
      displayName: Building frontend image
      script: docker build -t newecopeoplev1/frontend_dev ./frontend
    steps:
      displayName: Building backend image
      script: docker build -t newecopeoplev1/backend_dev ./backend
      # docker build -t newecopeoplev1/backend_dev ./backend
      # docker build -t newecopeoplev1/nginx_dev ./nginx
- stage: Push
  displayName: Push images
  jobs:
  - job: Push
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    displayName: Pushing images for development
    # steps:
    # - script: |
    #     docker login -u $(DOCKER_ID) -p $(DOCKER_PWD)
        # docker push newecopeoplev1/frontend_dev
        # docker push newecopeoplev1/backend_dev
        # docker push newecopeoplev1/nginx_dev
        # docker push newecopeoplev1/nginx_template_dev