# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*

resources:
- repo: self

variables:
  projectName: 'Eco Phase 2'

stages:
- stage: develop
  displayName: Build/Push Images for Development
  jobs:  
  - job: Develop
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    timeoutInMinutes: 30
    displayName: Check if change is for develop branch
    steps:
      - script: |
          docker build -t newecopeoplev1/frontend_dev ./frontend
          # docker build -t newecopeoplev1/backend_dev ./backend
          docker login -u $(DOCKER_ID) -p $(DOCKER_PWD)
          docker push newecopeoplev1/frontend_dev
          # docker push newecopeoplev1/backend_dev
- stage: master
  displayName: Build/Push images for Production
  jobs:
  - job: Master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Checking if change is for master branch
    steps:
      - script: | 
          docker build -t newecopeoplev1/frontend ./frontend
          docker build -t newecopeoplev1/backend ./backend
          docker login -u $(DOCKER_ID) -p $(DOCKER_PWD)
          docker push newecopeoplev1/frontend
          docker push newecopeoplev1/backend
