# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*

resources:
- repo: self

variables:
  projectName: 'Eco Phase 2'
  DOCKER_ID: $(DOCKER_ID)

stages:
- stage: Build
  displayName: Build/Push Images for Development
  jobs:  
  - job: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    timeoutInMinutes: 30
    displayName: Build images for development
    steps:
      - script: |
          docker build -t newecopeoplev1/frontend_dev ./frontend
          docker build -t newecopeoplev1/backend_dev ./backend
          docker login -u $(DOCKER_ID) -p $(DOCKER_PWD)
          docker push newecopeoplev1/frontend_dev
          docker push newecopeoplev1/backend_dev

      # - task: Docker@2
      #   displayName: Build frontend image
      #   inputs:
      #     command: build
      #     dockerfile: './frontend/Dockerfile'
      #     tags: '$(frontend)_dev'
      # - task: Docker@2
      #   displayName: Build backend image
      #   inputs:
      #     command: build
      #     dockerfile: './backend/Dockerfile'
      #     tags: '$(backend)_dev'
            
    #   displayName: Building frontend image
    #   - script: 
    #     docker build -t newecopeoplev1/frontend_dev ./frontend
    # steps:
    #   displayName: Building backend image
    #   script: docker build -t newecopeoplev1/backend_dev ./backend
      # docker build -t newecopeoplev1/backend_dev ./backend
      # docker build -t newecopeoplev1/nginx_dev ./nginx
- stage: Push
  displayName: Build/Push images for Production
  jobs:
  - job: Push
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Pushing images for development
    steps:
      - script: | 
          docker build -t newecopeoplev1/frontend ./frontend
          docker build -t newecopeoplev1/backend ./backend
          docker login -u $(DOCKER_ID) -p $(DOCKER_PWD)
          docker push newecopeoplev1/frontend
          docker push newecopeoplev1/backend
          # docker push newecopeoplev1/nginx_dev
          # docker push newecopeoplev1/nginx_template_dev

    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'Eco Development'
    #     repository: 'frontend_dev'
    #     command: 'push'
    #     tags: 'latest'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'Eco Development'
    #     repository: 'backend_dev'
    #     command: 'push'
    #     tags: 'latest'
