version: "3.4"

services:

  mssql_image:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "noPassword@247"
        ACCEPT_EULA: "Y"
    ports:
      - "3200:1433"

  backend:
    image: newecopeoplev1/backend_dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=server=mssql_image;Database=eco-appDb;user id=sa;password=noPassword@247;MultipleActiveResultSets=True
      - HOSTNAME=http://localhost
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
    depends_on:
      - mssql_image
    ports:
      - "5000:5000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  template:
    image: newecopeoplev1/template_dev
    ports:
      - "4000:4201"
