version: "3.4"

services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  frontend:
    image: newecopeoplev1/frontend_dev
    ports:
      - "4200:4200"

  backend:
    image: newecopeoplev1/backend_dev
    volumes:
      - ./db/StagingDb.db:/app/StagingDb.db
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - HOSTNAME=http://newecopeople.com
      - SENDGRID_APIKEY
    ports:
      - "5000:5000"