version: "3.4"

services:

  postgres_image:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root_user"
      POSTGRES_PASSWORD: "root_password"
      POSTGRES_DB: "app_db"

  backend:
    image: newecopeoplev1/backend_dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=host=postgres_image;port=5432;database=app_db;username=root_user;password=root_password
      - HOSTNAME=http://localhost
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
    depends_on:
      - postgres_image
    ports:
      - "5000:5000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  template:
    image: newecopeoplev1/template_dev
    ports:
      - "4000:4201"
