version: "3.4"

services:
  
  frontend:
    image: newecopeoplev1/frontend_dev
    ports:
      - "4200:4200"

  backend:
    image: newecopeoplev1/backend_dev
    volumes:
      - ..db/StagingDb.db:/app/StagingDb.db
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - HOSTNAME=http://newecopeople.com
    ports:
      - "5000:5000"

