version: "3.4"

services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    volumes:
      - /home/agent/app/db:/app/StagingDb.db
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - HOSTNAME=http://localhost
    ports:
      - "5000:5000"

  # nginx_template:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx_template
  #   ports:
  #     - "4000:4000"

  # template:
  #   build:
  #     context: ./template
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4201:4201"